---
name: CI Workflow Template for ansible-lint yamllint and Ansible Galaxy imports

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
'on':
  workflow_call:
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow
    secrets:
      GALAXY_API_KEY:
        description: 'This comes from the caller workflow'
        required: true
  # pull_request:
  # schedule:
  #   - cron: "0 4 * * 5"
  push:
    branches:
      - main
      - master
    tags:
      - '*'

defaults:
  run:
    working-directory: 'sleif.ws'

jobs:
  lint:
    name: Lint and Ansible Galaxy import
    runs-on: ubuntu-latest
    # environment: build
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'sleif.ws'

      - name: Secret test
        run: |
          echo "${{ secrets.GALAXY_API_KEY }}"
          echo ${GITHUB_REPOSITORY%/*}
          echo ${GITHUB_REPOSITORY#*/}

      # https://github.com/marketplace/actions/setup-python
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install yamllint ansible ansible-lint

      - name: Yaml lint code.
        run: |
          yamllint --version
          yamllint .

      - name: Ansible lint code.
        run: |
          ansible-lint --version
          ansible-lint .

      - name: Import Galaxy Role
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        # env:
        #   GALAXY_API_KEY: "API: ${{ secrets.GALAXY_API_KEY }}"
        run: |
          ansible-galaxy role import -s https://galaxy.ansible.com/api/ --api-key "${{
          secrets.GALAXY_API_KEY }}" "${GITHUB_REPOSITORY%/*}" "${GITHUB_REPOSITORY#*/}"
